name: Deploy Databricks Jobs

on:
  push:
    branches:
      - main

env:
  TF_IN_AUTOMATION: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Terraform Init and Validate
      run: |
        # Loop through each folder in the repository root
        for dir in */; do
          # Navigate into each folder
          cd $dir
          # Run Terraform Init and Validate
          ls
          #terraform init
          #terraform validate
          # Navigate back to repository root
          cd ..
        done

    - name: Run Terraform Plan
      run: |
        # Loop through each folder in the repository root
        for dir in */; do
          # Navigate into each folder
          cd $dir
          # Run Terraform Plan
          ls
          #terraform plan
          # Navigate back to repository root
          cd ..
        done

    - name: Run Terraform Apply
      run: |
        # Loop through each folder in the repository root
        for dir in */; do
          # Navigate into each folder
          cd $dir
          # Run Terraform Apply
          ls
          #terraform apply -auto-approve
          # Navigate back to repository root
          cd ..
        done
